### ISSUE TITLE
mdn: adapt for the new ui again

### ISSUE THREAD

**Issue by myfreeer** [website-local/mdn-local#534]
https://hacks.mozilla.org/2022/03/a-new-year-a-new-mdn/
This always changing thing makes things difficult.

- [x] remove new useless-for-offline things (https://github.com/website-local/mdn-local/issues/628)
  - mdn plus
  - notecard  localized-content-note inline neutral
  - `#nav-footer.page-footer`
  - .contributor-spotlight
  - `#on-github.on-github`
  - languages-switcher-menu open-on-focus-within
  - or maybe .article-actions
- [x] hide search by default again (https://github.com/website-local/mdn-local/issues/628)
- [x] keep the copyright notice (https://github.com/website-local/mdn-local/issues/628)
- [x] update the rendering of the compatibility table (https://github.com/website-local/mdn-local/issues/629)
- [x] update the ui scripts of the compatibility table (https://github.com/website-local/mdn-local/issues/630)
- [x] make ui features work
  - [x] top menu for ~~pc~~(script makes no different on a pc), tablet, mobile (https://github.com/website-local/mdn-local/issues/783)
  - [x] dark/light/default theme (https://github.com/website-local/mdn-local/issues/782)
  - [x] scroll and highight on right menu
  - [x] update ui actions the compatibility table
  - [x] left menu on mobile (https://github.com/website-local/mdn-local/issues/784)
  - [x] left menu scroll into view (https://github.com/website-local/mdn-local/issues/784) and (https://github.com/website-local/mdn-local/commit/d5dec05066e57e595af180b20eadf605e1caf299)
